<?php
/**
* @author Tridhya Tech
* @copyright Copyright (c) 2023 Tridhya Tech Ltd (https://www.tridhyatech.com)
* @package Tridhyatech_LayeredNavigation
 */
?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
/** @var Tridhyatech\ProductFilter\ViewModel\JsConfig $filterJsConfig */
$filterJsConfig = $block->getData('viewModel');

?>
<div id="product-filter-init"></div>

<script type="text/x-magento-init">
    {
        "#product-filter-init": {
            "Tridhyatech_LayeredNavigation/js/init": <?= /** @noEscape */ $filterJsConfig->getJson() ?>
        }
    }
</script>

<?php /** Fix for browser history after ajax-queries */?>
<script>
    require([
        "tridhyatech/product-filter/action",
        "domReady!"
    ], function (filterAction) {
        var oldOnpopstate = window.onpopstate;
        window.onpopstate = function (event) {
            if (typeof oldOnpopstate === 'function') oldOnpopstate();
            filterAction.setSkipHistory(true);
            if (event.state !== null) {
                filterAction.applyUrl(window.location.href);
            }
        };
    });
</script>
