<?php
/**
 * @author    Tridhya Tech
 * @copyright Copyright (c) 2023 Tridhya Tech Ltd (https://www.tridhyatech.com)
 * @package   Tridhyatech_LayeredNavigation
 */
?>
<?php
/**
 * @var \Tridhyatech\LayeredNavigation\Block\RenderPrice $block
 */
?>

<ol class="items">
    <?php /**
           * @var \Tridhyatech\LayeredNavigation\Model\Catalog\Layer\Filter\Item[] $filterItems
           */?>
    <?php foreach ($filterItems as $filterItem): ?>

        <?php $isRadio = $filterItem->getFilter()->getIsRadio(); ?>
        <li class="item">
            <?php if ($filterItem->getCount() > 0) : ?>
                <a href="<?php echo $block->escapeUrl($filterItem->getUrl()) ?>"
                    <?php if ($filterItem->getIsActive()) : ?>class="selected"<?php 
                    endif; ?>
                    data-pr-filter="item"
                    data-variable="<?php echo $block->escapeHtml($filterItem->getFilter()->getRequestVar()) ?>"
                    data-value="<?php echo $block->escapeHtml($filterItem->getValueString()) ?>"
                    <?php if ($isRadio) : ?>data-radio="true"<?php 
                    endif; ?>
                    rel="nofollow">
                    <span><?php echo /** * @noEscape */ $filterItem->getLabel() ?>
                    <?php if ($this->helper(\Magento\Catalog\Helper\Data::class)->shouldDisplayProductCountOnLayer()) : ?>
                        <span class="count">
                            <?php echo $block->escapeHtml($filterItem->getCount()) ?>
                            <span class="filter-count-label">
                                <?php echo $block->escapeHtml(__($filterItem->getCount() == 1 ? 'item' : 'items')) ?>
                            </span>
                        </span>
                    <?php endif; ?>
                    </span>
                </a>
            <?php else: ?>
                <span class="attr-dis<?php if ($filterItem->getIsActive()) : ?> selected<?php 
               endif; ?>">
                <?php echo $block->escapeHtml($filterItem->getLabel()) ?>
                <?php if ($this->helper(\Magento\Catalog\Helper\Data::class)->shouldDisplayProductCountOnLayer()) : ?>
                    <span class="count">
                        <?php echo $block->escapeHtml($filterItem->getCount()) ?>
                        <span class="filter-count-label">
                            <?php echo $block->escapeHtml(__($filterItem->getCount() == 1 ? 'item' : 'items')) ?>
                        </span>
                    </span>
                <?php endif; ?>
                </span>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
